<?php

namespace AppBundle\Repository;

/**
 * SalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRepository extends \Doctrine\ORM\EntityRepository
{
}
